//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefuelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refuels
    {
        public int Id { get; set; }
        public System.DateTime DateOf { get; set; }
        public decimal TotalFuelCostInEuros { get; set; }
        public Nullable<int> TotalDistanceTraveled { get; set; }
        public string UserFK { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
